### ISSUE TITLE
Not removing lawnstep installation

### ISSUE THREAD

**Issue by Bberx** [skittles9823/QuickSwitch#1]
## Description
It does not removing lawnstep installation, also causes bootloop if you disable(not uninstall) lawnstep with quickstep co-existing.

## Expected Behavior
Should remove lawnstep previous installation as per v1.0.6 changelog

## Actual Behavior
it dosent detect and remove lawnstep installation

## Steps to Reproduce

1.  Install quickstep via TWRP
2. reboot
3. lawnstep is still in magisk manager

## Environment
* Device: Xiaomi Mi A2 Lite 4GB/64GB "daisy"
* Android version: 9
* Quickstep version:  1.0.6
* Rom: stock pie

**Comment by skittles9823** [comment]
I just pushed an update to fix this.
