### ISSUE TITLE
OnePlus recents not working on my phone

### ISSUE THREAD

**Issue by MarcAnt01** [skittles9823/QuickSwitch#14]
OnePlus 3 running Lineage OS 17.1 official

OnePlus launcher works and is set to default, but I still have AOSP recents.

[quickswitch-logs.zip](https://github.com/skittles9823/QuickSwitch/files/4536212/quickswitch-logs.zip)

**Comment by skittles9823** [comment]
Could you run `cmd overlay dump xyz.paphonb.quickstepswitcher.overlay` and show me the output please.

**Comment by MarcAnt01** [comment]
![image](https://user-images.githubusercontent.com/43090263/80364954-173c1f00-8887-11ea-9a65-6375196edd24.png)

**Comment by skittles9823** [comment]
Sorry for the late reply.

```STATE_NO_IDMAP``` means your rom has some broken overlays, you can ask your devices maintainer to implement [this](https://github.com/AOSiP-Devices/device_oneplus_sdm845-common/commit/9c560f95731eb28310a81048612edaec15853f1d)

**Comment by MarcAnt01** [comment]
@skittles9823 my device is non-Treble A-only, does it apply the same?

**Comment by skittles9823** [comment]
I believe so. Treble or A only shouldn't matter in this instance.

**Comment by MarcAnt01** [comment]
OK, thanks for the support, closing this issue
