### ISSUE TITLE
Using QuickSwitch module causes some apps to lag, when used with Magisk Hide

### ISSUE THREAD

**Issue by Gieted** [skittles9823/QuickSwitch#15]
Some apps, including:

- [Revolut](https://play.google.com/store/apps/details?id=com.revolut.revolut&hl=en_US)
- [Allegro](https://play.google.com/store/apps/details?id=pl.allegro&hl=en_US)

lags heavily when QuickSwitch module is enabled and Magisk Hide is turned on for them. This happens even with Pixel Launcher as recents provider, so it must be caused by QuickSwitch directly.

Steps to reproduce:
1. Install QuickSwitch module
2. Download Revolut app
3. Compare Revolut's responsiveness with Magisk Hide enabled and disabled for it

Android version: 10
Magisk version: 20.4 (20400)
Magisk Manager version: 7.5.1 (267)
QuickSwitch version: 3.1.6-2

[Quick Switch logs](https://github.com/skittles9823/QuickSwitch/files/4722586/quickswitch-logs.zip)

**Comment by skittles9823** [comment]
@Gieted It's a magisk issue and it's been discussed before in #7

**Comment by Gieted** [comment]
Ah I see, thanks for info. It's quite unfortunate that bug like this exists.
