### ISSUE TITLE
Ability to select webview disappears on OxygenOS 12 

### ISSUE THREAD

**Issue by e8genius** [skittles9823/QuickSwitch#22]
Tried it OxygenOS 12 and on ColorOS 12 based on on Android 12 (OnePlus 9 Pro) 

When installing a quick switch through the magisk module, after rebooting the system, the ability to select a google default webview disappears.
The system continues to work without the ability to select webview and many applications stop working correctly.

As a way out, I put a third-party webview from bromite and it worked correctly. But I would like to be able to use Google's webview

**Comment by Mo7ammedSalah** [comment]
Same here on OnePlus 9 pro but i fix the issue temporary by install WebView manager here

https://www.androidacy.com/downloads/?view=%2540Magisk-Modules%2540Webview_Manager

Also some of my apps stopped working and immediately closed !!

**Comment by skittles9823** [comment]
Make sure you're running the latest version of QuickSwitch (3.2.0) it fixed several issues with OOS 12, I can't be sure this issue is one that was fixed but it's possible it might have been.
