### ISSUE TITLE
Not compatible with android 12?

### ISSUE THREAD

**Issue by jacob153** [skittles9823/QuickSwitch#26]
I am on a pixel 6 on Android 12 build SP2A.220405.004
Lawnchair 12 launcher has quickswich support as well as the pixelated launcher but neither of them work. When opening the quickswich app is says "not compatible with android 12" underneath the launchers listed. Here is a screenshot of what I mean too. Thought it may have been something I did so I factory reset and still with no luck.
![Screenshot_20220412-133308](https://user-images.githubusercontent.com/35608018/163021063-869f6a58-ee98-4b5e-9632-bdd088c5f6c5.png)

**Comment by jacob153** [comment]
To any one with this problem, talking to devs with lawnchair it is not completely a launcher issue if you are in 12L or 12.1 QuickSwitch does not work you'll want to re flash 12 re-root then use QuickSwitch with your desired supported launcher.

**Comment by skittles9823** [comment]
> if you are in 12L or 12.1 QuickSwitch does not work

Incorrect. It's the launcher that doesn't support QuickSwitch on 12.1, QuickSwitch itself shouldn't require an update to work.

**Comment by jacob153** [comment]
> > if you are in 12L or 12.1 QuickSwitch does not work
> 
> Incorrect. It's the launcher that doesn't support QuickSwitch on 12.1, QuickSwitch itself shouldn't require an update to work.

In that case do you know of any launchers that do work with this on Android 12L?
