### ISSUE TITLE
Lawnchair is being shown non compatible

### ISSUE THREAD

**Issue by sho-blackz** [skittles9823/QuickSwitch#34]
I have also open a issue on lawnchair issue page.![Screenshot_2022-08-27-21-39-47-279_xyz.paphonb.quickstepswitcher.jpg](https://user-images.githubusercontent.com/112008643/187069885-c96ede7d-1f12-4dd1-b6f1-30952bd77b39.jpg)

- Device: Xiaomi 11i (Indian version with china rom)
- Model no.:210911161
-OS: stock rom MIUI CHINA  13.0.4 stable
-Android version: 12.0
- App version: 12.1.0 Alpha 4

If you can help me with this annoying discomfort of MIUI ,which does not let us change the launcher without getting navigation bar at the bottom.

**Comment by skittles9823** [comment]
You'd need to use Lawnchair 12.0.0, Lawnchair 12.1 is for Android 12.1 only.
