### ISSUE TITLE
Can't drag and drop icons to homescreen

### ISSUE THREAD

**Issue by xChAmeLIoNz** [skittles9823/QuickSwitch#35]
I'm currently using lawnchair Version 12.1.0 Alpha 4 on xiaomi mi pad 5 with ArrowOs 12.1.
If I use lawnchair without QS I'm able to drag apps into homescreen but whenever I use QuickSwitch I cannot drag applications to the homescreen.

**Comment by skittles9823** [comment]
This is a Lawnchair issue, not a QuickSwitch issue.
