### ISSUE TITLE
While switching between providers, previous provider is not un-systemized.

### ISSUE THREAD

**Issue by ThatNerdyPikachu** [skittles9823/QuickSwitch#4]
For example, when switching between Lawnchair and Quickstep — Lawnchair is still systemized.

**Comment by skittles9823** [comment]
Is this in 1.1.2 or 1.1.3 alpha?

**Comment by ThatNerdyPikachu** [comment]
I don’t know — I installed via MM

**Comment by ThatNerdyPikachu** [comment]
I’m assuming 1.2?

**Comment by skittles9823** [comment]
Yea 1.1.2 then. Well I'm expecting to update to 1.1.3 very soon. But it'll be switching templates, so I'm still working out how to do a smooth transition on the user side of things.

**Comment by ThatNerdyPikachu** [comment]
Also, for some reason after resetting my provider — I always boot into recovery, and am now flashing my stock images. Could this be a potential bug with the module itself?

**Comment by skittles9823** [comment]
Possibly. It could also be fixed in 1.1.3 already. I'll push what I have when I update it my side again when the template gets finalised and hopefully it'll fix the issue.

**Comment by skittles9823** [comment]
Could you let me know if this was fixed for you in 2.0.x?

**Comment by ThatNerdyPikachu** [comment]
It was not.

**Comment by ThatNerdyPikachu** [comment]
(Switched provider to default, switched to Lawnchair, switched back to default, Lawnchair is still a system app.)

**Comment by skittles9823** [comment]
Interesting. Have you tried a complete uninstall of the module? Tbh if it's still a system app it leads me to believe you've restored a TiBa backup when Lawnchair was the recents provider or something similar.

**Comment by ThatNerdyPikachu** [comment]
I did not. And yes, I have.

**Comment by ThatNerdyPikachu** [comment]
as in, I've tried to uninstall the module, and I've never restored a backup.

**Comment by skittles9823** [comment]
If you uninstall the module is Lawnchair still a system app?

**Comment by ThatNerdyPikachu** [comment]
Yes

**Comment by ThatNerdyPikachu** [comment]
and the only module I've used that affects Lawnchair is QuickSwitch

**Comment by skittles9823** [comment]
If it remains a system app then it's not QuickSwitch that's systemized it. QuickSwitch removes all traces of itself on uninstallation.

I suggest you uninstall QuickSwitch and find exactly where it's located. Running
`su -c pm path ch.deletescape.lawnchair.ci` will tell you where it is. If it says it's in /data/app then go into app info and select uninstall all updates and run the command again and you'll see the system path.

**Comment by ThatNerdyPikachu** [comment]
I can't uninstall all updates -- there's no option (Android Pie)

**Comment by skittles9823** [comment]
By uninstall updates I meant the three dot button > uninstall updates.
![three dot button](https://i.imgur.com/PMrwVEr.png)
![uninstall updates](https://i.imgur.com/LUawyzr.png)

**Comment by ThatNerdyPikachu** [comment]
I think I fixed it... nice.

I don't know how...

But anyways, thank you for your help!

P.S. What theme is that?

**Comment by skittles9823** [comment]
Wew. Glad you got it solved.

The themes are Ethereal and Outline X.
