### ISSUE TITLE
[FEATURE] Add permissions on the go?

### ISSUE THREAD

**Issue by heckarman** [skittles9823/QuickSwitch#45]
Can a new feature be added where the app grants necessary permissions required by the launcher to work?  
I use GrapheneOS as my daily driver and the OS does not support Pixel Launcher what so ever. It requires `READ_DEVICE_CONFIG` permission to be set which is the first permission that it asks for and crashes for. Can quickswitch support granting of permission at the time of configuring the launcher to be used as recents provider?

**Comment by skittles9823** [comment]
QuickSwitch should [automatically grant](https://github.com/skittles9823/QuickSwitch/blob/master/quickswitch#L257) all permissions defined in the apps manifest at the time of switching providers.
