### ISSUE TITLE
APK missing in latest release

### ISSUE THREAD

**Issue by debnath-d** [skittles9823/QuickSwitch#48]
APK file seems to be missing from the latest release: https://github.com/skittles9823/QuickSwitch/releases/tag/4.0.0

**Comment by skittles9823** [comment]
it is there.

**Comment by debnath-d** [comment]
@skittles9823 I'm still not able to see it. This is what I'm looking at:

![image](https://github.com/skittles9823/QuickSwitch/assets/16205994/adfdcbd8-30b1-4186-94bd-d324df111cf8)

Can you please provide me a direct link so that I can download the apk?

**Comment by skittles9823** [comment]
Flash the zip. It will install the apk.

**Comment by debnath-d** [comment]
Can you please update the README.md to reflect this change in installation instructions? The current instructions are (https://github.com/skittles9823/QuickSwitch/blob/4.0.0/README.md#installation):

    1. Install the latest QuickSwitch apk from the [Telegram channel](https://t.me/QuickstepSwitcherReleases) or [GitHub releases](https://github.com/skittles9823/QuickSwitch/releases).
    2. Open the QuickSwitch app that was installed.
    3. Select a different launcher as your recents provider.
    4. Reboot.
    5. Verify your new recents provider is correct.
    6. Set the new recents provider as the default launcher.
    7. Profit.

It's not clear to me how exactly to flash the zip.
