### ISSUE TITLE
Fingerprint Button and video

### ISSUE THREAD

**Issue by SivalalR** [skittles9823/QuickSwitch#5]
Oneplus 3t, magisk 19, latest beta pie build used quickswitch 203 with latest lawnchair. Fingerprint button is not working. And video is black in youtube. I can provide more info if needed, but a guidence is much appreciated.

**Comment by skittles9823** [comment]
If you disable the QuickSwitch module does it restore functionality?

**Comment by SivalalR** [comment]
Yes
