### ISSUE TITLE
Text OCR in Recents non-functional while using QuickSwitch

### ISSUE THREAD

**Issue by suppai** [skittles9823/QuickSwitch#6]
The text OCR feature to copy text from app views in Recents does not seem to be functional while using QuickSwitch for me, whereas it works without it (even when Pixel Launcher isn't the default launcher). 

Am using Lawnchair 2.0-2168 on a Pixel 3 XL running stock Android.

**Comment by skittles9823** [comment]
Copy from recents is a Pixel Launcher exclusive feature for now. It only works when the Pixel Launcher is the recents provider

**Comment by suppai** [comment]
Fwiw, with the dysfunctional but partially working state QuickSwitch currently leaves Android Q devices in after being enabled then disabled, text OCR does function despite Lawnchair V2 being the default launcher/home app.

**Comment by skittles9823** [comment]
It should function with any launcher being the default home app since the Pixel Launcher still is the recents provider.

**Comment by ErickHoward** [comment]
Are there any updates on this? I still can't use OCR with the latest version of quick switch.
