### ISSUE TITLE
OxygenOS 14 System Launcher isn't compatible with Android 14?

### ISSUE THREAD

**Issue by Swap-File** [skittles9823/QuickSwitch#69]
I was trying to use QuickSwitch 4.0.3 on my OnePlus 12 (CPH2583) running OxygenOS 14.0.0.810 with Lawnchair 14 beta 2.

If I launch QuickSwitch, select Lawnchair and reboot, I can no longer pull up a recents screen.  I tried the Nightly version of Lawnchair and observed the same behavior.  The gesture just seems to do nothing.

But even weirder, once I switch my provider away from the default System Launcher, I can't switch back.  Quickswitch claims that the System Launcher that is included with OxygenOS is incompatible with Android 14.

Any ideas? (See screenshot below)

![image](https://github.com/skittles9823/QuickSwitch/assets/3854710/c3e6d0a7-54b9-4ee7-a75e-b1582b64c1bd)

**Comment by skittles9823** [comment]
That would be due to OOS Launcher targeting a different SDK, the app checks for targetSdk of the launcher or special QuickSwitch min/maxSdk metadata. To go back to stock reset the recents provider from the three dot menu of the app.

**Comment by Swap-File** [comment]
Is there any way for a user like me to check what SDKs are supported, and what SDK my phone is using?

Or is the easiest solution to try it and see if it works?

**Comment by skittles9823** [comment]
Well the stock launcher should always work, but there is no need to set the stock launcher via QuickSwitch. A14 is SDK 34.
