### ISSUE TITLE
QuickSwitch app source code

### ISSUE THREAD

**Issue by dvdmunckhof** [skittles9823/QuickSwitch#8]
I was looking into using Lawnchair v2 with QuickSwitch, and was curious how QuickSwitch works when installing it. However, I'm not able to find the source code of the app, just the APK. Am I overlooking the source code of the app, or is it not open source? If not, I'd like to request it being open sourced, especially since it's being run with system privileges.

Thanks in advance!

**Comment by skittles9823** [comment]
Currently the app is closed source as Paphon isn't exactly happy with the code.

However, QuickSwitch v3.0.0 will be getting a completely rewritten module and app and Paphon plans to open source that.
